### ISSUE TITLE
NLTK stopwords resource download required

### ISSUE THREAD

**Issue by zsunpku** [DS-BootCamp-Collaboratory-Columbia/AY2017-2018-Winter#2]
If encounter with a LookupError: 

> **********************************************************************
>   Resource 'corpora/stopwords.zip/stopwords/' not found.  Please
>   use the NLTK Downloader to obtain the resource:  >>>
>   nltk.download()

please consider add 
`nltk.download('stopwords')`
before Step 2.

**Comment by wendy9217** [comment]
If you come to problems like "Resource 'corpora/stopwords' not found.", please refer to [this link](https://stackoverflow.com/questions/26693736/nltk-and-stopwords-fail-lookuperror).

**Comment by tz33cu** [comment]
Updated
